name: Build new version

on:
    push:
        branches: [development]
    pull_request:
        branches: [master]
    workflow_dispatch:

jobs:
    build-extension:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Remove extra files and especific git folders
              run: rm -rf README.md TODO.md LICENSE .git .github

            - name: Create extension's zip files
              run: zip autolingo-extension-zip *

            - name: Get actual date for version name.
              id: actual-date
              run: echo "DATE=$(date +'%d.%m.%y')" >> $GITHUB_ENV

            - name: Create release
              id: create-release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: release
                  release_name: Version ${{ steps.actual-date.outputs.DATE }}
                  draft: true
                  prerelease: false
                  owner: ${{ github.actor }}

            - name: Upload assets for release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create-release.outputs.upload_url }}
                  asset_path: ./autolingo-extension-zip.zip
                  asset_name: autolingo.zip
                  asset_content_type: application/zip
