name: nightly.link

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
          only_changed: True

      - uses: actions/checkout@v2

      - name: Remove README file
        run: rm README.md


      - name: Remove TODO file
        run: rm TODO.md
        
        
      - name: Remove .git dir
        run: rm -r .git
        
        
      - name: Remove .github dir
        run: rm -r .github
      
      
      - name: Remove .whitespace file
        run: rm .whitespace
      
      
      - uses: actions/upload-artifact@v2
        with:
          name: AutolingoExtension
          path: .
