name: nightly.link build artifact 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Remove README file
        run: rm README.md


      - name: Remove TODO file
        run: rm TODO.md
        
        
      - name: Remove .git directory
        run: rm .git
        
        
      - name: Remove .github directory
        run: rm .github
        
      - uses: actions/upload-artifact@v2
        with:
          name: AutolingoExtension
          path: .
