name: Build new version

on:
    push:
        branches: [development]
    pull_request:
        branches: [master]

jobs:
    build-extension:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Remove extra files
              run: rm README.md TODO.md LICENSE

            - name: Remove especific git folders
              run: rm -rf .git .github

            - name: Create extension's zip files
              run: zip autolingo-extension-zip ./*

            - name: Create release
              id: create-release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                  tag_name: release
                  release_name: Release ${{ github.ref }}
                  draft: true
                  prerelease: false

            - name: Upload assets for release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create-release.outputs.upload_url }}
                  asset_path: ./autolingo-extension-zip.zip
                  asset_name: Autolingo.zip
